apiVersion: v1
entries:
  microcks:
  - apiVersion: v2
    appVersion: 1.6.1
    created: "2022-11-25T17:51:31.069143+01:00"
    description: Microcks - API Mocking and Testing
    digest: e7171269d78156940fbe7caa6c7ec78ee7172789c083ef0e9f050b253b1f0c75
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.6.1.tgz
    version: 1.6.1
  - apiVersion: v2
    appVersion: 1.6.0
    created: "2022-09-09T18:15:27.033598+02:00"
    description: Microcks - API Mocking and Testing
    digest: 57aa7e7cc12516f5516121af73b9c730959a3bfbb17ba9fa45a6fa7c112e910e
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v2
    appVersion: 1.5.2
    created: "2022-05-16T18:23:24.590651+02:00"
    description: Microcks - API Mocking and Testing
    digest: 8ecb2bad1dfb0b75567d167d2814e46623616f7d08804a9bcc1ed7e0676757ba
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.5.2.tgz
    version: 1.5.2
  - apiVersion: v2
    appVersion: 1.5.1
    created: "2022-04-07T17:23:37.538083+02:00"
    description: Microcks - API Mocking and Testing
    digest: ce1e7e9ad47aae4465bd39593ba4fcaf66b27d0719d9e791bb219237ace2f3be
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.5.1.tgz
    version: 1.5.1
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2022-01-13T16:04:12.100292+01:00"
    description: Microcks - API Mocking and Testing
    digest: b58567e9a5ef48d8f873df5f9feaeb343679091834abb294f344366961a2b5e9
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v2
    appVersion: 1.4.1
    created: "2021-10-04T15:00:26.868107+02:00"
    description: Microcks - API Mocking and Testing
    digest: 6f92f16daeb7943ab0fc52243ae628b2d0904d31ba97d1700739f9f4bed9d9fc
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.4.1.tgz
    version: 1.4.1
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2021-07-01T13:48:48.696087+02:00"
    description: Microcks - API Mocking and Testing
    digest: 9b21d8dc650f685dcf383e4eab8ce4e42150a66f6af3328d3e841ab83b622a9f
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 1.2.1
    created: "2021-04-28T16:23:32.186281+02:00"
    description: Microcks - API Mocking and Testing
    digest: 5b042619369a28758ac97585a03fe2d4c7cc6474aada3d1d79e472f396ad73e8
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2021-02-17T14:49:45.42224+01:00"
    description: Microcks - API Mocking and Testing
    digest: 1e0140301bf5227c0f83d8c9f439da2ba61eb015427a7b6420536a08fda3b3a3
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2020-10-26T11:57:40.275004+01:00"
    description: Microcks - API Mocking and Testing
    digest: 2d5b188a474c23694a541a5229a81284763d6abd6aa24c2db27bca40c9568f2d
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2020-08-12T17:58:15.613767+02:00"
    description: Microcks - API Mocking and Testing
    digest: be3127fa74bd335400902136a79054a9ed691780f8bdd7dbff5297dbabd14852
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v2
    appVersion: 0.9.2
    created: "2020-05-19T22:27:37.083585+02:00"
    description: Microcks - API Mocking and Testing
    digest: 3726102749cf9ad9a0343cb8d636475a0e0d6938f068c59149049263dbe69b68
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-0.9.2.tgz
    version: 0.9.2
  - apiVersion: v2
    appVersion: 0.9.1
    created: "2020-05-05T12:16:40.804923+02:00"
    description: Microcks - API Mocking and Testing
    digest: f5b7e288241c55452b18791011294ee015be77cc44a311ee830d9fd83d0becc1
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-0.9.1.tgz
    version: 0.9.1
  - apiVersion: v2
    appVersion: 0.9.0
    created: "2020-04-17T12:37:27.551484+02:00"
    description: Microcks - API Mocking and Testing
    digest: a93922c8ed835d6545269b4b18727405482f60b3b756cdaf7d193912949a8ef7
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: 0.8.0
    created: "2020-02-26T09:21:04.15071+01:00"
    description: Microcks - API Mocking and Testing
    digest: b7dbd5de6d564486889586d9d595ab445e540a22ad7604def2b0e1d290d620c6
    home: https://microcks.io
    icon: https://microcks.io/images/microcks-big.png
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/microcks/microcks/
    - https://microcks.io
    type: application
    urls:
    - https://microcks.io/helm/microcks-0.8.0.tgz
    version: 0.8.0-helm-3.kube-1.17
generated: "2022-11-25T17:51:31.058023+01:00"
